### PR TITLE
Update domains.txt

### PR DESCRIPTION
**Pull request by josephworks**
Massive update to hosts list

### CODE REVIEW

**Comment by GardeningTool** [comment]
Going to leave this PR open for now, I haven't decided to add in non gaming/IP logger domains yet.

**Comment by BobIsMyManager** [comment]
1 million lines jeez

**Comment by DrAGoniPenguin** [comment]
Ayo, I clicked on raw and it froze my google chrome for a solid minute

**Comment by BobIsMyManager** [comment]
Same lmao

**Comment by josephworks** [comment]
Well yeah
image
Please be sure to have 2+Gb ram free and an 8th gen i7 or above.
Also, you should also use an GPU powered display (not onboard graphics) when loading the raw view.

**Comment by BobIsMyManager** [comment]
I only have onboard graphics 🥺

**Comment by BobIsMyManager** [comment]
Nvm it works on my phone for some reason lmao

**Comment by DrAGoniPenguin** [comment]
Dammit my i5-4460 from 2014 aint gonna hold up

**Comment by GardeningTool** [comment]
WAY too many domains

**Comment by BobIsMyManager** [comment]
Did the program crash or something?

**Comment by GardeningTool** [comment]
Let's just say the Windows DNS client was NOT happy

**Comment by BobIsMyManager** [comment]
Lmao

**Comment by josephworks** [comment]
I had a suspicion that was going to happen
oh well...

**Pull request merged**
