### PR TITLE
steancomunnity.ru

### PR DESCRIPTION
**Pull request by BobIsMyManager**
token logger

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
solves #14

**Comment by GardeningTool** [comment]
Added, thank you, though next time please attach proof of it being a logger.

**Comment by BobIsMyManager** [comment]
and multiple people do this in every single channel they can speak in on every server they are in

**Comment by BobIsMyManager** [comment]
and when I ask them, they said they never sent that message

**Comment by GardeningTool** [comment]
Alright, that's sufficient.

**Pull request merged**
