### PR TITLE
Tournament predator.xyz

### PR DESCRIPTION
**Pull request by BobIsMyManager**
Sus site, Guy just posts it and if you press login it makes the site look like steam even when it’s not

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
Probably a token logger, and definitely a phishing site

**Comment by BobIsMyManager** [comment]
GitHub moment, made the commits on both branches

**Comment by GardeningTool** [comment]
Can't merge this PR since the branch is deleted

**Comment by BobIsMyManager** [comment]
Yea, GitHub was having a moment and commited the changes to both branches so I deleted this one

**Pull request closed without merging**
