### PR TITLE
steamcommunytu.ru

### PR DESCRIPTION
**Pull request by BobIsMyManager**

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
25B94AE4-AC40-48CB-A1B3-B93AD863DCAE

**Comment by BobIsMyManager** [comment]
I've also noticed that now when people post them they no longer embed

**Comment by GardeningTool** [comment]
Do you by any chance know who's behind this?

**Comment by BobIsMyManager** [comment]
If anyone did, they would probably be locked up by now

**Comment by KotTenRat** [comment]
obraz
side seems to died, this doesn't look like mc community malware, more like some cs:go cheat cracks, etc.

**Comment by BobIsMyManager** [comment]
Yea, that’s why they say they’re giving away csgo skins

**Comment by KotTenRat** [comment]
right, i will investigate into it.

**Comment by BobIsMyManager** [comment]
👍

**Pull request merged**
