### PR TITLE
discord-nitro.site

### PR DESCRIPTION
**Pull request by BobIsMyManager**
2AD939ED-A56C-48CC-B19D-9374480A2CA1
AE320399-BF29-426F-BB9C-DFB1AB935EEA
690BD666-CFF3-44FA-A4F9-5CD657223DEA
13AA5ABF-0B94-4498-AB3D-EF3C9BACF422
102B8DC8-7691-4DE4-9C7E-6780EC60949E
Omg free nitro wtf

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
The sign in discord button redirects to fake steam lmfao, this is the worse one yet

**Comment by GardeningTool** [comment]
Saw this one earlier, was gonna add it myself once my flight landed. Thanks for the PR!

**Comment by BobIsMyManager** [comment]
> was gonna add it myself once my flight landed. 
Ur on ur phone while on the airplane?!?

**Comment by GardeningTool** [comment]
Nah, I was at the airport when I saw it

**Pull request merged**
